Artifactory: ArtifactoryUnified
Pipelines:
  name: pet_clinic_config_server
GitRepo:
  name: PetClinicProjectGitRepo
  path: Samples/pet-clinic-project/spring-petclinic-microservices/spring-petclinic-config-server
  provider: PetClinicProjectGitRepo
Step1 :
  name: bld_config_server
Step2 :
  name: bld_config_server_docker_image
