Resource1 :
  name : MvnBuildConfigServerDockerImage
  imageName : docker.artifactory-unified.soleng-us.jfrog.team/configserverdockerimage
Resource2 :
  name : BuildMavenConfigServer_ProduceDockerImage_BuildInfo
  imageName : docker.artifactory-unified.soleng-us.jfrog.team/configserverdockerimage
Resource3 :
  name : PetClinicGitRepo
  gitProvider : Github_SolEng
  path: jfrog/SolEngDemo
  branch : pet-clinic-project

Artifactory: ArtifactoryUnified
Pipelines:
  name: BuildMavenConfigServer_ProduceDockerImage
GitRepo:
  name: PetClinicGitRepo
  path: Samples/pet-clinic-project/spring-petclinic-microservices/spring-petclinic-config-server
  provider: PetClinicGitRepo
Step1 :
  name: mvn_bld_config_server
Step2 :
  name: convert_mvnbuild_dockerimage
  dockerFileLocation: Samples/pet-clinic-project/spring-petclinic-microservices/spring-petclinic-config-server
  dockerImageName: docker.artifactory-unified.soleng-us.jfrog.team/configserverdockerimage
  outputResourceName: MvnBuildConfigServerDockerImage
Step3 :
  name: push_config_server_docker_image
  outputResourceName : BuildMavenConfigServer_ProduceDockerImage_BuildInfo




